# Generated by Django 5.2.9 on 2025-12-15 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('life_stage', models.CharField(max_length=30)),
                ('tracking_duration', models.IntegerField()),
                ('pain_score', models.IntegerField()),
                ('avg_cycle_length', models.IntegerField()),
                ('cycle_length_variation', models.IntegerField()),
                ('avg_bleeding_days', models.IntegerField()),
                ('bleeding_volume_score', models.IntegerField()),
                ('intermenstrual_episodes', models.IntegerField()),
                ('cycle_variation_coefficient', models.FloatField()),
                ('pattern_disruption_score', models.IntegerField()),
                ('irregularity_prediction', models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], max_length=20)),
                ('irregularity_probability', models.FloatField()),
                ('next_cycle_prediction', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptom_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='tracker.cycle')),
            ],
        ),
    ]
