# Generated by Django 5.1.3 on 2026-03-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_cycle_irregularity_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='irregularity_prediction',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], max_length=20, null=True, verbose_name='Prediction Status'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='irregularity_probability',
            field=models.FloatField(blank=True, null=True, verbose_name='Chance of Irregularity'),
        ),
    ]
