# Generated by Django 5.1.3 on 2026-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_cycle_height_cycle_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='missed_periods',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
