# Generated by Django 5.2.9 on 2025-12-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_cycle_next_cycle_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='avg_bleeding_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='avg_cycle_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='bleeding_volume_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='cycle_length_variation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='cycle_variation_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='intermenstrual_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='life_stage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='pain_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='pattern_disruption_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='tracking_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
