# Generated by Django 5.2.9 on 2025-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_cycle_age_alter_cycle_avg_bleeding_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='irregularity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
